// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC66nTdzNk9vxNjbc8dBJge8DOduYhe4_c',
    appId: '1:489829230928:web:39bd986fec32d0b1372455',
    messagingSenderId: '489829230928',
    projectId: 'chat-app-aa50a',
    authDomain: 'chat-app-aa50a.firebaseapp.com',
    storageBucket: 'chat-app-aa50a.appspot.com',
    measurementId: 'G-LHXPRFTB9Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4qsl7iI4tQ-ZcQzJRrtZNpcasZSbERC0',
    appId: '1:489829230928:android:1a3619f5c8dc0f24372455',
    messagingSenderId: '489829230928',
    projectId: 'chat-app-aa50a',
    storageBucket: 'chat-app-aa50a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFKgAa643r_GKwIOjgh33buS9gCHfwuz8',
    appId: '1:489829230928:ios:2d6ea2751ad087d6372455',
    messagingSenderId: '489829230928',
    projectId: 'chat-app-aa50a',
    storageBucket: 'chat-app-aa50a.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFKgAa643r_GKwIOjgh33buS9gCHfwuz8',
    appId: '1:489829230928:ios:2d6ea2751ad087d6372455',
    messagingSenderId: '489829230928',
    projectId: 'chat-app-aa50a',
    storageBucket: 'chat-app-aa50a.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC66nTdzNk9vxNjbc8dBJge8DOduYhe4_c',
    appId: '1:489829230928:web:2830819c5a454012372455',
    messagingSenderId: '489829230928',
    projectId: 'chat-app-aa50a',
    authDomain: 'chat-app-aa50a.firebaseapp.com',
    storageBucket: 'chat-app-aa50a.appspot.com',
    measurementId: 'G-TS69BGCKFS',
  );
}
